### ISSUE TITLE
Horizontal and Vertical Scrolling broken with recent update of CMS

### ISSUE THREAD

**Issue by dbmcdonald** [tomahg/Gulla.Episerver.SqlStudio#3]
Since upgrading to CMS 12.22 the menu moved to the left instead of the top and I no longer can scroll.  So to see anything past the first 5 rows you have to export to excel.

![image](https://github.com/tomahg/Gulla.Episerver.SqlStudio/assets/14058401/6f33331b-0e37-4f12-ace1-5d2bf52033b7)

**Comment by tomahg** [comment]
Thanks for reporting, but this should have been fixed in Episerver.CMS.UI 12.22.4.

https://world.optimizely.com/documentation/Release-Notes/ReleaseNote/?releaseNoteId=CMS-29327

Have you tested the latest version of the CMS?

**Comment by dbmcdonald** [comment]
We can try. We updated sqlstudio trying to fix it, but not cms



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Tomas Hensrud Gulla ***@***.***>
Date: 8/25/23 6:07 PM (GMT-06:00)
To: "tomahg/Gulla.Episerver.SqlStudio" ***@***.***>
Cc: David McDonald ***@***.***>, Author ***@***.***>
Subject: Re: [tomahg/Gulla.Episerver.SqlStudio] Horizontal and Vertical Scrolling broken with recent update of CMS (Issue #3)


Thanks for reporting, but this should have been fixed in Episerver.CMS.UI 12.22.4.

https://world.optimizely.com/documentation/Release-Notes/ReleaseNote/?releaseNoteId=CMS-29327

Have you tested the latest version of the CMS?

**Comment by tomahg** [comment]
I've just tested with a site updated to Episerver.CMS.UI 12.22.4, and the scrollbars are back. Both horizontal and vertical.

I'll leave this issue open until you've verified.

**Comment by dbmcdonald** [comment]
Perfect, thanks.  I put it on your backlog to get this updated this week already.  You can close this and if there is a problem, I will let you know.  Thanks!  Love the tool!

--------
David B McDonald, Director of Development
Brilliance Business Solutions
+1-414-425-4069 x120

**Comment by tomahg** [comment]
Thanks.

Closing the issue, as it's fixed in Episerver.CMS.UI 12.22.4.
