### ISSUE TITLE
SQL Timeout configuration

### ISSUE THREAD

**Issue by furoTmark** [tomahg/Gulla.Episerver.SqlStudio#5]
I am using the CMS 11 version of this plugin and I was wondering if there is a way to add a timeout configuration to the plugin.
Currently, I often get timeouts when running queries or operations with this tool.

(Happy to help out, if possible)

**Comment by tomahg** [comment]
Hi @furoTmark, you should be able to achieve this by adding a timeout value to your connection string like this `;Connection Timeout=30` at the end.

Format:
https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectiontimeout?view=netframework-4.6.1

In the version for CMS 12 it is possible to configure a custom connection string that is only used by the addon, not the website. For CMS 11, this is not explicitly added.

However, you could add an extra connection string like this, with the desired timeout, using an initialization module. Then, you will get a dropdown list in the plugin UI where you can select between the two available connection string.

``` csharp
[InitializableModule]
public class ContentTypeInitialization : IInitializableModule
{
    public void Initialize(InitializationEngine context)
    {
        var dao = ServiceLocator.Current.GetInstance<DataAccessOptions>();
        dao.ConnectionStrings.Add(new ConnectionStringOptions() { Name = "SQL Addon", ConnectionString = "Data Source=db.net;Database=mydb;User Id=uid;Password=pwd;Connection Timeout=30" });
    }
    public void Uninitialize(InitializationEngine context)
    {
    }
}
```

Should show up like this.
![image](https://github.com/user-attachments/assets/5cf442fa-19e9-43bd-bf72-701f38801261)

Let me know if it works out ok :)

**Comment by furoTmark** [comment]
Thanks for the help, it just what we needed.
